### ISSUE TITLE
Was the end-user authentication of the Salesforce connector been deprecated?

### ISSUE THREAD

**Issue by hoyo** [slackapi/deno-slack-hub#63]
I had used the Salesforce connector of deno-slack-hub with Slack Workflow​.

```typescript
import { Connectors } from "deno-slack-hub/mod.ts";
 
// ...
 
MyWorkflow.addStep(
  Connectors.Salesforce.functions.CreateRecord,
  {
    salesforce_access_token: { credential_source: "END_USER" },
    salesforce_object_name: "Task",
    metadata: {
      // ...
    },
  },
);
```

When I recently ran `slack deploy` recently, the following error message appeared and it seems not to work.

> 📝 This value has been deprecated. Please update. (end_user_oauth_requires_last_interactor)

Is there any solution of this problem?

**Comment by mwbrooks** [comment]
Hey @hoyo 👋🏻 Thanks for using the Slack CLI and Deno SDK 🙂 

Can you tell us whether the `end_user_oauth_requires_last_interactor` message is an error message or warning message?

**Comment by mwbrooks** [comment]
Hello again @hoyo 👋🏻 I've been talking with a few backend engineers at Slack. If possible, would you mind adding `user_context_source: "LAST_INTERACTOR"` to your code sample to see if it removes the error/warning?

```typescript
MyWorkflow.addStep(
  Connectors.Salesforce.functions.CreateRecord,
  {
    salesforce_access_token: { credential_source: "END_USER", user_context_source: "LAST_INTERACTOR" },
    salesforce_object_name: "Task",
    metadata: {
      // ...
    },
  },
);
```

The reasoning is that the Slack API defaults to `user_context_source="CALLER_USER"`  for backwards compatibility, but `credential_source="END_USER"` requires `user_context_source="LAST_INTERACTOR"`. If this unblocks you, then I'll bring it back to the team so that we can improve our documentation and code samples. 🙇🏻

**Comment by hoyo** [comment]
Thank you for your response.

I tried your advice, and `the end_user_oauth_requires_last_interactor` error no longer appears

However, the workflow is not being executed, so there may be an error in another part of the code

I have implemented a workflow that includes a Salesforce connector to be triggered via the workflow button. After running `slack run` or `slack deploy`, but the workflow that includes the `Connectors.Salesforce.functions.CreateRecord` step is not responding. If I comment out the `Connectors.Salesforce.functions.CreateRecord` step, the other steps work normally.

**Comment by WilliamBergamin** [comment]
It appears theirs been a breaking change to the definition of `Connectors.Salesforce.functions.CreateRecord` on the backend 🤔 

It now seems to be using a type that is not yet defined by the deno SDK, I opened up this [PR](https://github.com/slackapi/deno-slack-sdk/pull/390) to add it, reviews will soon be welcome

But this missing type caused the automated job generating the source code of deno-slack-hub to fail, I suspect this may be the underlying issue, I suspect `Connectors.Salesforce.functions.CreateRecord` is out of date

**Comment by WilliamBergamin** [comment]
@hoyo [deno_slack_hub@3.0.0](https://deno.land/x/deno_slack_hub@3.0.0) is out and should resolve this issue 🚀 

Let us know if we can close this issue!

**Comment by hoyo** [comment]
@WilliamBergamin Thank you for your support.

Unfortunately, the problem was not solved when I have updated [deno_slack_hub@3.0.0](https://deno.land/x/deno_slack_hub@3.0.0) and [deno_slack_sdk@2.15.0](https://deno.land/x/deno_slack_sdk@2.15.0).

The workflow including a step with `Connectors.Salesforce.functions.CreateRecord`, my shortcut trigger will not respond and there is no message in log. If I commenting out the step with `Connectors.Salesforce.functions.CreateRecord`, it will enable it to work normally.

**Comment by WilliamBergamin** [comment]
I was able to reproduce this behavior, It seems this may be a backend issue related to the external authentication of the connector

**Comment by hoyo** [comment]
@WilliamBergamin How is the situation of the issue now?
